name: adata_tords
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::anndata2ri=1.3.1
  - conda-forge::anndata=0.10.7
  - conda-forge::r-seurat=5.0.3
  - conda-forge::numpy<2.0
  - bioconda::bioconductor-s4vectors
  - bioconda::bioconductor-singlecellexperiment