name: environment
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python=3.8
  - r
  - r-essentials
  - r-seurat
  - r-tidyverse
  - r-signac
  - r-optparse
  - r-data.table
  - docopt
  - numpy
  - pandas
  - networkx
  - matplotlib
  - cython
  - pydot
  - graphviz
  - gseapy
  - r-networkd3
  - r-shinywidgets
  - r-dt
  - r-shinythemes
  - r-shinyhelper
  - arboreto
  - importlib-metadata
  - bioconductor-dcanr
  - bioconductor-decoupler
  - bioconductor-dorothea
  - bioconductor-omnipathr
  - r-sceasy
